name: Publish Docker Images

on:
 push:
    branches:
      - 'main'

jobs:
  push_to_docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup qemu
        uses: docker/setup-qemu-action@v2
      
      - name: Build and push Docker images
        id: build-and-push-latest
        uses: docker/build-push-action@v3.1.1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: isenganime/hugofirebase:latest
          labels: ${{ steps.meta.outputs.label }}